name: Test Suite

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  test_basic:
    runs-on: ubuntu-latest
    name: Basic Usage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t . -t newrelic-install-action
      - name: Test install
        run: docker run -it \
          -e NEW_RELIC_API_KEY="NRAK-any" \
          -e NEW_RELIC_INVENTORY="1.1.1.1,1.1.1.2" \
          -e NEW_RELIC_SSH_USER="ec2-user" \
          -e NEW_RELIC_SSH_KEY_FILE="/path/to/file.pem" \
          -e NEW_RELIC_INSTALL_TARGETS="something,else" \
          newrelic-install-action
        env:
          NEW_RELIC_ACCOUNT_ID: "1234"
